### ISSUE TITLE
Warn that `babel-runtime` will be embedded if not declared as dependency

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/neutrino-preset-taskcluster#4]
I think we should require that `babel-runtime` is declared a dependency... Right now if it's not present in `package.json` it'll be embedded in `index.bundle.js`, that seems like a really bad thing.

@eliperelman, in a node project if we have two libraries requiring `babel-runtime: "^6.0.0"` then I think they'll both get the same instance of babel-runtime, hence, it won't be loaded into memory twice.

**Comment by eliperelman** [comment]
With the latest Neutrino versions, I'm not sure this is a concern anymore. Neutrino now uses Webpack's `externals`, and [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) to exclude external dependencies from being included in a bundle, so these should be required as expected. I'll close this, but we can re-open if we find there is something insufficient there.
